
name: armTemplateDeployment #CI

# Controls when the workflow will run
on:

  workflow_dispatch:

env:
  # Set the Azure subscription ID as an environment variable
  AZURE_SUBSCRIPTION_ID: '13400b0a-b2f7-409d-99a6-0c5dee058434'
  # Set the Azure resource group name as an environment variable
  AZURE_RESOURCE_GROUP: 'rg-github-actions' 
  LOCATION: 'westus' # Set the Azure location as an environment variable
  REGION: West US # Set the Azure region as an environment variable


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  armDeploy: #build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}



      
      - name: Deploy Resource Group ${{ env.AZURE_RESOURCE_GROUP}}
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: "${{ env.REGION }}"
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP}}
          template: ./arm-templates/resourcegroup.json
         # parameters: ./azuredeploy.parameters.json
          deploymentName: rg-github-actions-deployment
         # location: westus
         # deploymentMode: Incremental  # default is Incremental, can also be Complete

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        id: deployStorageAccount
        with:
          scope: resourcegroup
          region: "${{ env.REGION }}"
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP}}
          template: ./arm-templates/storageaccount.json
          parameters:
             ./arm-templates/storageaccount.parameters.json
             storageAccountName=saxyz1234zza

          deploymentName: rg-github-actions-storage-deployment

      - run: echo "BlobUri"
      - run: echo  ${{ steps.deployStorageAccount.outputs.BlobUri }}
        # This will output the storage account name from the deployment step
        # You can use this output in subsequent steps if needed
      - name: Deploy ARM Template
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          region: "${{ env.REGION }}"
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP}}
          template: ./arm-templates/virtualmachine.json
          parameters:  adminUsername=myadmin adminPublicKey="${{ secrets.AZURE_ADMIN_PUBLIC_KEY }}" location=${{ env.LOCATION}} vmSize=Standard_B1s
