name: "Bicep Deployment Workflow"

on:
  push:
    branches:
      - add-storage-account
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: '13400b0a-b2f7-409d-99a6-0c5dee058434'
  AZURE_RESOURCE_GROUP: 'rg-github-actions-bicep'
  LOCATION: 'westus'

jobs:
  bicepAzCliDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.AZURE_RESOURCE_GROUP }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location "${{ env.LOCATION }}" --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy virtual network
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file ./bicep-templates/virtualnetwork.bicep --parameters location="${{ env.LOCATION }}" vNetPrefix="bicepazcli" 