name: "Bicep Deployment Workflow"

on:
  push:
    branches:
      - add-storage-account
  workflow_dispatch:

env:
  # Set the Azure subscription ID as an environment variable
  AZURE_SUBSCRIPTION_ID: '13400b0a-b2f7-409d-99a6-0c5dee058434'
  # Set the Azure resource group name as an environment variable
  AZURE_RESOURCE_GROUP: 'rg-github-actions-bicep' 
  LOCATION: 'westus' # Set the Azure location as an environment variable
  REGION: 'West US' # Set the Azure region as an environment variable (quoted for consistency)

jobs:
  bicepAzCliDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location "${{ env.LOCATION }}"

      - name: Deploy Resource Group Template
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} \
              --template-file ./bicep-templates/resourcegroup.bicep \
              --parameters location="${{ env.LOCATION }}" \
              --name rg-github-actions-deployment

      - name: Deploy Virtual Network
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --template-file ./bicep-templates/virtualnetwork.bicep \
              --parameters location="${{ env.LOCATION }}" vNetPrefix="bicepazcli" \
